name: ci-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'

    - name: Build
      run: |
        go mod tidy && git diff --exit-code
        go build ./cmd/... ./pkg/...

    - name: Test
      run: GOPATH=/home/runner/go go test ./cmd/... ./pkg/... ./test/...
